### ISSUE TITLE
Create an Artifact to Document the Submission and Processing of Lab Reports for Discovery Report Presentation

### ISSUE THREAD

**Issue by hie1** [CDCgov/prime-field-teams#22]
**User Story** 
As the LADOH, I want a clear understanding of the current state of the components that make up our disease surveillance system for COVID-19 tracking, monitoring, reporting, and other surveillance activities so that I understand the limitations and challenges of the current "system" and can make decisions about next step solutions.

**Acceptance Criteria**
- Representation of knowledge in an artifact or artifacts that represent how COVID lab results get from the submitting entity to LADOH to CDC and also to facilitate contact tracing (show the components of their "disease surveillance system."
- Highlight any pain points in the existing process specific to the technology (e.g. lack of features in the system)
- Include sufficient detail and explanation in Lucid Chart so that it can be ported into a presentation-ready format in Google Slides.

**Tasks**

- [ ] Iteratively develop artifact in Lucid Chart until a final artifact is complete; update after each interview (Aurora)
- [ ] Iteratively review artifact in Lucid Chart after each interview modification (Mike)
- [ ] Transfer artifact to Google Slides (Hayley)
