### ISSUE TITLE
Create Artifacts to Represent Technology Challenges in Current State Uncovered in Discovery

### ISSUE THREAD

**Issue by hie1** [CDCgov/prime-field-teams#23]
**User Story**
As a member of LADOH, I want to understand any multi-step challenges in a visual way so that I can effectively evaluate information and make decisions on next-step solutions.

**Acceptance Criteria**
- Provide sufficient detail to 

**Tasks**
- [ ] Through the interview process identify additional pain points and challenges about LADOH current state (Mike, Aurora, Hayley)
- [ ] Represent challenges verbally/qualitatively via Mural and slides (Hayley)
- [ ] Represent challenges visually - technical details; utilize Lucid Chart (Aurora)
- [ ] Transfer Lucid chart diagrams to Google Slides (Hayley)
