### ISSUE TITLE
Develop Potential Solutions

### ISSUE THREAD

**Issue by hie1** [CDCgov/prime-field-teams#24]
**User Story**
As LADOH, I want to understand potential solutions that will solve the challenges outlined in the current state environment so that I can understand my options. 

**Acceptance Criteria**
- Must have a sufficient understanding of the current state before starting this card.
- The solution must provide a high-level description of each solution and how it aligns to a pain point(s)
- Any solutions should receive early buy-in at the LADOH co-creation session with Brick Green; if no buy-in, remove them from the report out
- Any solution developed must be filtered through the lens of LADOH, CDC, USDS, and APHL - would it be useful, usable, and acceptable for these groups?

**Tasks**
- [ ] Obtain sufficient understanding of current state by 3/10/21
- [x] Develop assets for use in an ideation brainstorming session (Hayley)
- [ ] Internal brainstorming session to collaboratively develop solutions (Hayley, Aurora, Mike) 3/11/21
- [ ] Host co-creation workshop with Brick Green (LADOH) 3/15 - 3/17/21
