### ISSUE TITLE
For Selected Solutions, Develop Recommended Path Forward

### ISSUE THREAD

**Issue by hie1** [CDCgov/prime-field-teams#25]
**User Story**
As LADOH, I want to understand how I will move forward on the selected solutions presented by Agile Six so that I can determine if they are a good fit for my team.

**Acceptance Criteria**
- Completed for the selected solutions that come out of co-creation ideation session with Brick Green
- Include timeline
- Include level of effort
- Including any relevant architecture diagrams
- Take into account any resources LADOH might have available to them including CDC and APHL - think outside the scope of Agile Six technical assistance work
- If appropriate, include a recommendation for technical support from Agile Six

**Tasks**
- [ ] Meet with APHL to understand ways that APHL supports states (Mike, Hayley, Aurora)
- [ ] Transfer selected solutions from co-creation session to discovery report out deck (Hayley)
- [ ] Host an internal brainstorming session to develop paths forward for each selected solution
- [ ] Meet with USDS to get buy-in for proposed solutions and possible paths forward
- [ ] Modify discovery report out deck with selected solutions and paths forward accordingly after USDS meeting
