### ISSUE TITLE
Create a Space for Logging Our Reusable Components for the Playbook

### ISSUE THREAD

**Issue by hie1** [CDCgov/prime-field-teams#31]
**User Story**
As a member of the team, I want to be able to add reusable components easily so that they can be considered for a final playbook and/or reuse with another entity or state.

**Acceptance Criteria**
- Thorough enough to record already identified areas of reusable components but flexible enough to incorporate anything new
- Easy to find, navigate, understand, and alter/add to as any member of the team

**Tasks**
- [ ] Create a space or spaces in available tools (e.g. Notion, Google Drive)
- [ ] Include existing [work completed [](https://docs.google.com/document/d/1wjj2x1T1l91Q26r79r0GmIyXyj9EbO1VaFTp5xWcRpg/edit) as part of our 30-day deliverable 
- [ ] Determine a method and cadence with the engineering team for recording new reusable components
